apiVersion: v1
kind: Service
metadata:
  annotations:
    tunnels.networking.cloudflare-operator.io/cr: tunnel-sample
    tunnels.networking.cloudflare-operator.io/ns: default
  creationTimestamp: null
  name: whoami-test
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: whoami
status:
  loadBalancer: {}
