# permissions for end users to edit accessservicetokens.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: accessservicetoken-editor-role
rules:
- apiGroups:
  - networking.cloudflare-operator.io
  resources:
  - accessservicetokens
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.cloudflare-operator.io
  resources:
  - accessservicetokens/status
  verbs:
  - get
