# permissions for end users to view accessidentityproviders.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: accessidentityprovider-viewer-role
rules:
- apiGroups:
  - networking.cloudflare-operator.io
  resources:
  - accessidentityproviders
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.cloudflare-operator.io
  resources:
  - accessidentityproviders/status
  verbs:
  - get
