# permissions for end users to view accessapplications.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: accessapplication-viewer-role
rules:
- apiGroups:
  - networking.cfargotunnel.com
  resources:
  - accessapplications
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.cfargotunnel.com
  resources:
  - accessapplications/status
  verbs:
  - get
