# permissions for end users to view accessgroups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: accessgroup-viewer-role
rules:
- apiGroups:
  - networking.cfargotunnel.com
  resources:
  - accessgroups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.cfargotunnel.com
  resources:
  - accessgroups/status
  verbs:
  - get
