# permissions for end users to edit accessidentityproviders.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: accessidentityprovider-editor-role
rules:
- apiGroups:
  - networking.cloudflare-operator.io
  resources:
  - accessidentityproviders
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.cloudflare-operator.io
  resources:
  - accessidentityproviders/status
  verbs:
  - get
