# permissions for end users to view accesstunnels.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: cloudflare-operator
    app.kubernetes.io/managed-by: kustomize
  name: accesstunnel-viewer-role
rules:
- apiGroups:
  - networking.cloudflare-operator.io
  resources:
  - accesstunnels
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.cloudflare-operator.io
  resources:
  - accesstunnels/status
  verbs:
  - get
