# permissions for end users to edit accessgroups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: accessgroup-editor-role
rules:
- apiGroups:
  - networking.cfargotunnel.com
  resources:
  - accessgroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.cfargotunnel.com
  resources:
  - accessgroups/status
  verbs:
  - get
