# permissions for end users to view accessservicetokens.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: accessservicetoken-viewer-role
rules:
- apiGroups:
  - networking.cfargotunnel.com
  resources:
  - accessservicetokens
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.cfargotunnel.com
  resources:
  - accessservicetokens/status
  verbs:
  - get
