# permissions for end users to edit accessapplications.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: accessapplication-editor-role
rules:
- apiGroups:
  - networking.cfargotunnel.com
  resources:
  - accessapplications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.cfargotunnel.com
  resources:
  - accessapplications/status
  verbs:
  - get
