# permissions for end users to view clustertunnels.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clustertunnel-viewer-role
rules:
- apiGroups:
  - networking.cloudflare-operator.io
  resources:
  - clustertunnels
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.cloudflare-operator.io
  resources:
  - clustertunnels/status
  verbs:
  - get
