# permissions for end users to view devicesettingspolicies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: devicesettingspolicy-viewer-role
rules:
- apiGroups:
  - networking.cfargotunnel.com
  resources:
  - devicesettingspolicies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.cfargotunnel.com
  resources:
  - devicesettingspolicies/status
  verbs:
  - get
