# permissions for end users to view deviceposturerules.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: deviceposturerule-viewer-role
rules:
- apiGroups:
  - networking.cloudflare-operator.io
  resources:
  - deviceposturerules
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.cloudflare-operator.io
  resources:
  - deviceposturerules/status
  verbs:
  - get
