# permissions for end users to edit deviceposturerules.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: deviceposturerule-editor-role
rules:
- apiGroups:
  - networking.cfargotunnel.com
  resources:
  - deviceposturerules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.cfargotunnel.com
  resources:
  - deviceposturerules/status
  verbs:
  - get
