# permissions for end users to edit gatewayconfigurations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gatewayconfiguration-editor-role
rules:
- apiGroups:
  - networking.cloudflare-operator.io
  resources:
  - gatewayconfigurations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.cloudflare-operator.io
  resources:
  - gatewayconfigurations/status
  verbs:
  - get
