# permissions for end users to view gatewayrules.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gatewayrule-viewer-role
rules:
- apiGroups:
  - networking.cfargotunnel.com
  resources:
  - gatewayrules
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.cfargotunnel.com
  resources:
  - gatewayrules/status
  verbs:
  - get
