# permissions for end users to edit gatewaylists.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gatewaylist-editor-role
rules:
- apiGroups:
  - networking.cloudflare-operator.io
  resources:
  - gatewaylists
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.cloudflare-operator.io
  resources:
  - gatewaylists/status
  verbs:
  - get
