# permissions for end users to edit networkroutes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: networkroute-editor-role
rules:
- apiGroups:
  - networking.cloudflare-operator.io
  resources:
  - networkroutes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.cloudflare-operator.io
  resources:
  - networkroutes/status
  verbs:
  - get
