# permissions for end users to view networkroutes.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: networkroute-viewer-role
rules:
- apiGroups:
  - networking.cfargotunnel.com
  resources:
  - networkroutes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.cfargotunnel.com
  resources:
  - networkroutes/status
  verbs:
  - get
