# permissions for end users to edit privateservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: privateservice-editor-role
rules:
- apiGroups:
  - networking.cfargotunnel.com
  resources:
  - privateservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.cfargotunnel.com
  resources:
  - privateservices/status
  verbs:
  - get
