---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - gatewayclasses
  - gateways
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - gatewayclasses/status
  - gateways/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - gateways/finalizers
  verbs:
  - update
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - httproutes
  - tcproutes
  - udproutes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.cloudflare-operator.io
  resources:
  - accessapplications
  - accessgroups
  - accessidentityproviders
  - accessservicetokens
  - accesstunnels
  - cloudflarecredentials
  - clustertunnels
  - deviceposturerules
  - devicesettingspolicies
  - dnsrecords
  - gatewayconfigurations
  - gatewaylists
  - gatewayrules
  - networkroutes
  - privateservices
  - tunnelbindings
  - tunnels
  - virtualnetworks
  - warpconnectors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.cloudflare-operator.io
  resources:
  - accessapplications/finalizers
  - accessgroups/finalizers
  - accessidentityproviders/finalizers
  - accessservicetokens/finalizers
  - cloudflarecredentials/finalizers
  - clustertunnels/finalizers
  - deviceposturerules/finalizers
  - devicesettingspolicies/finalizers
  - dnsrecords/finalizers
  - gatewayconfigurations/finalizers
  - gatewaylists/finalizers
  - gatewayrules/finalizers
  - networkroutes/finalizers
  - privateservices/finalizers
  - tunnelbindings/finalizers
  - tunnels/finalizers
  - virtualnetworks/finalizers
  - warpconnectors/finalizers
  verbs:
  - update
- apiGroups:
  - networking.cloudflare-operator.io
  resources:
  - accessapplications/status
  - accessgroups/status
  - accessidentityproviders/status
  - accessservicetokens/status
  - accesstunnels/status
  - cloudflarecredentials/status
  - clustertunnels/status
  - deviceposturerules/status
  - devicesettingspolicies/status
  - dnsrecords/status
  - gatewayconfigurations/status
  - gatewaylists/status
  - gatewayrules/status
  - networkroutes/status
  - privateservices/status
  - tunnelbindings/status
  - tunnelingressclassconfigs/status
  - tunnels/status
  - virtualnetworks/status
  - warpconnectors/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - networking.cloudflare-operator.io
  resources:
  - tunnelgatewayclassconfigs
  - tunnelingressclassconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingressclasses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses/finalizers
  verbs:
  - update
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses/status
  verbs:
  - get
  - patch
  - update
