# permissions for end users to view tunnels.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tunnel-viewer-role
rules:
- apiGroups:
  - networking.cloudflare-operator.io
  resources:
  - tunnels
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.cloudflare-operator.io
  resources:
  - tunnels/status
  verbs:
  - get
