# permissions for end users to view virtualnetworks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: virtualnetwork-viewer-role
rules:
- apiGroups:
  - networking.cfargotunnel.com
  resources:
  - virtualnetworks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.cfargotunnel.com
  resources:
  - virtualnetworks/status
  verbs:
  - get
