# permissions for end users to view warpconnectors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: warpconnector-viewer-role
rules:
- apiGroups:
  - networking.cfargotunnel.com
  resources:
  - warpconnectors
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - networking.cfargotunnel.com
  resources:
  - warpconnectors/status
  verbs:
  - get
