# permissions for end users to edit warpconnectors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: warpconnector-editor-role
rules:
- apiGroups:
  - networking.cloudflare-operator.io
  resources:
  - warpconnectors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.cloudflare-operator.io
  resources:
  - warpconnectors/status
  verbs:
  - get
