apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  labels:
    app.kubernetes.io/name: cloudflare-operator
    app.kubernetes.io/managed-by: kustomize
  name: cloudflare-tunnel
  annotations:
    # Set to "true" to make this the default IngressClass
    ingressclass.kubernetes.io/is-default-class: "false"
spec:
  # Controller identifier - matches the Ingress controller implementation
  controller: cloudflare-operator.io/ingress-controller
  # Parameters reference - points to the TunnelIngressClassConfig
  parameters:
    apiGroup: networking.cloudflare-operator.io
    kind: TunnelIngressClassConfig
    name: default
    namespace: cloudflare-operator-system
