apiVersion: v1
kind: Service
metadata:
  name: whoami-test
  namespace: testing-crd
  annotations:
    tunnels.networking.cloudflare-operator.io/cr: tunnel-sample
    tunnels.networking.cloudflare-operator.io/ns: default
spec:
  selector:
    app: whoami
  ports:
    - port: 80
      targetPort: 80
